server:
  port: 9093
spring:
  application:
    name: jak_09_payment
  cloud:
    discovery:
      enabled: true
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/jak_09_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Salim.1325k
    hikari:
      connection-timeout: 3000000
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
